apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-backend
  namespace: production
  labels:
    app: retail-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-backend
  template:
    metadata:
      labels:
        app: retail-backend
    spec:
      containers:
      - name: api
        image: umasankar33/backendssl:1
        ports:
        - containerPort: 8080
          name: api-port
        env:
        - name: NODE_ENV
          value: "local"  # 👈 Activates our new code override path!
        - name: DB_HOST
          value: "local-postgres-service.production.svc.cluster.local"
        - name: DB_NAME
          value: "retail_prod"
        - name: DB_PORT
          value: "5432" 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-credentials
              key: DB_PASSWORD
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "150m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: retail-backend-service
  namespace: production
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: retail-backend