apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-frontend
  namespace: production
  labels:
    app: retail-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-frontend
  template:
    metadata:
      labels:
        app: retail-frontend
    spec:
      containers:
      - name: web-ui
        image: umasankar33/frentend:1
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:5000"
        - name: NODE_BE_URL
          value: "http://localhost:5000"
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: retail-frontend-service
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: retail-frontend